package com.example.navirom.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    ALBANIAN("sq", "Albanian", "Shqip")
}

enum class AppThemeMode(val titleEn: String, val titleSq: String) {
    DARK("Dark", "I errët"),
    LIGHT("Light", "I çelët"),
    SYSTEM("System Default", "Sipas sistemit")
}

object NaviromStrings {

    fun get(key: String, language: AppLanguage = AppLanguage.ENGLISH): String {
        val map = if (language == AppLanguage.ALBANIAN) albanianStrings else englishStrings
        return map[key] ?: englishStrings[key] ?: formatFallbackKey(key)
    }

    private fun formatFallbackKey(key: String): String {
        if (!key.contains("_")) return key
        return key.split("_")
            .filter { it.isNotBlank() }
            .joinToString(" ") { word ->
                word.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
            }
            .ifBlank { key }
    }

    private val englishStrings = mapOf(
        // Tabs
        "tab_library" to "Library",
        "tab_home" to "Library",
        "tab_playlists" to "Playlists",
        "tab_search" to "Search",
        "tab_offline" to "Offline",
        "tab_downloads" to "Offline",
        "tab_settings" to "Settings",

        // Subtabs
        "subtab_libraries" to "Libraries",
        "subtab_songs" to "Songs",
        "subtab_albums" to "Albums",
        "subtab_artists" to "Artists",
        "subtab_quick_mix" to "Server Mix",
        "subtab_recent" to "Recent",
        "recently_played_title" to "Recently Played",
        "recently_played_subtitle" to "Your recently played tracks",
        "empty_recent_title" to "No Recent Songs",
        "empty_recent_desc" to "Songs you play will appear here for quick access.",
        "server_libraries_title" to "Navidrome Server Libraries",
        "server_libraries_desc" to "Browse distinct music folders and libraries configured on your Navidrome server.",
        "btn_browse_library" to "Browse Library",
        "active_library_badge" to "ACTIVE LIBRARY",
        "all_libraries_title" to "All Music Folders",
        "all_libraries_desc" to "Combined collection from all configured server folders",
        "switch_library_prompt" to "Active Library",
        "sidebar_libraries_title" to "Server Libraries",
        "sidebar_open" to "Libraries",
        "sort_by" to "Sort by",
        "sort_name" to "Name (A-Z)",
        "sort_duration" to "Duration",
        "sort_recent" to "Recently Added",
        "sort_artist" to "Artist",
        "shake_detected_toast" to "Shake detected! Playing random track from %s",

        // Deck Actions & General Actions
        "deck_liked" to "Liked Songs",
        "deck_liked_sub" to "Your favorites",
        "deck_mix" to "Random Mix",
        "deck_mix_sub" to "25 random songs",
        "deck_shuffle" to "Shuffle All",
        "deck_shuffle_sub" to "Play entire library",
        "deck_discover" to "Discover",
        "deck_discover_sub" to "Explore new music",
        "play_all" to "Play All",
        "shuffle_all" to "Shuffle All",
        "play_cached" to "Play Downloaded",
        "clear_all_cache" to "Clear Cache",
        "offline_only" to "Offline Only",
        "sync_now" to "Sync Now",
        "saved_servers" to "Saved Servers",
        "tracks_count" to "tracks",
        "settings_crossfade" to "Audio Crossfade",
        "settings_crossfade_duration" to "Crossfade Duration",
        "settings_crossfade_seconds" to "Seconds (1 - 20s)",
        "settings_crossfade_desc" to "Smoothly crossfade between consecutive tracks.",
        "multi_libraries_selected" to "%d Libraries Selected",
        "select_all_libraries" to "Select All Libraries",
        "clear_library_selection" to "Clear Selection",
        "all_libraries_combined" to "All Libraries (Unified)",
        "downloads_title" to "Offline Downloads",
        "empty_downloads" to "No Downloaded Tracks",
        "empty_downloads_desc" to "Downloaded tracks will appear here for offline listening.",

        // Library & Empty State
        "empty_library_title" to "No Music Found",
        "empty_library_desc" to "Connect to your Navidrome server or auto-scan your local network in Settings to load your music library.",
        "btn_connect_server" to "Configure Server",
        "btn_scan_network" to "Auto-scan Network",
        "album_tracks_count" to "%d tracks",
        "album_duration" to "%d min",
        "btn_play_all" to "Play All",
        "btn_shuffle" to "Shuffle",
        "btn_download_all" to "Download All",
        "badge_offline" to "OFFLINE",
        "badge_online" to "ONLINE",
        "top_picks" to "Top Albums",
        "featured_artists" to "Artists",

        // Search
        "search_hint" to "Search songs, albums, artists...",
        "search_tracks" to "Songs",
        "search_albums" to "Albums",
        "search_artists" to "Artists",
        "search_no_results" to "No results found for \"%s\"",
        "search_recent" to "Explore your Navidrome server with instant search",
        "search_hint_sub" to "Type artist, album name, or track title",
        "search_history_title" to "Recent Searches",
        "search_history_clear" to "Clear all",

        // Playlists
        "playlists_title" to "Playlists",
        "btn_create_playlist" to "New Playlist",
        "dialog_create_playlist" to "Create New Playlist",
        "dialog_playlist_name" to "Playlist Name",
        "btn_create" to "Create",
        "btn_cancel" to "Cancel",
        "empty_playlists" to "No playlists found",
        "empty_playlists_desc" to "Create custom playlists or sync existing ones from your Navidrome server.",
        "delete_playlist" to "Delete Playlist",

        // Offline
        "offline_title" to "Offline Cache",
        "offline_cached_total" to "Downloaded Music",
        "offline_mode_toggle" to "Offline Only Mode",
        "offline_mode_desc" to "Only play downloaded songs and prevent cellular data usage",
        "btn_play_cached" to "Play Cached Tracks",
        "btn_clear_cache" to "Clear Cache",
        "empty_cache_title" to "No Downloaded Tracks",
        "empty_cache_desc" to "Download any song or full album to listen without an internet connection.",

        // Settings
        "settings_title" to "Settings",
        "server_status_title" to "Server Status",
        "server_connected" to "Connected",
        "server_disconnected" to "Disconnected",
        "server_sync_now" to "Sync Library",
        "server_config_title" to "Navidrome Server",
        "protocol" to "Protocol",
        "host" to "Host / IP Address",
        "host_placeholder" to "192.168.1.50 or music.server.com",
        "port" to "Port (Default 4533)",
        "port_placeholder" to "4533",
        "username" to "Username",
        "password" to "Password",
        "use_token_auth" to "Token Authentication (MD5/Salt)",
        "use_token_auth_desc" to "Recommended for Navidrome & Subsonic security",
        "btn_connect" to "Connect to Server",
        "btn_connecting" to "Connecting...",
        "btn_auto_scan" to "Auto-scan local network",
        "btn_stop_auto_scan" to "Stop Auto-Scan",
        "btn_scanning" to "Scanning subnet for Navidrome...",
        "scan_no_network_title" to "No Network Connection",
        "scan_no_network_desc" to "Device is offline. Connect to Wi-Fi or a local network to auto-scan for Navidrome servers.",
        "library_filter" to "Library Filter",
        "all_libraries" to "All Libraries",
        "select_folder" to "Select Music Folder",

        // Appearance & Language
        "appearance_title" to "Appearance & Language",
        "theme_mode" to "Theme Mode",
        "theme_dark" to "Dark Mode",
        "theme_light" to "Light Mode",
        "theme_system" to "System Default",
        "language" to "Language",
        "lang_english" to "English",
        "lang_albanian" to "Shqip (Albanian)",

        // Player & Queue
        "now_playing" to "Now Playing",
        "up_next" to "Up Next",
        "queue_title" to "Queue",
        "play_next" to "Play Next",
        "add_to_queue" to "Add to Queue",
        "quality_hi_res" to "FLAC / Lossless",
        "quality_standard" to "Standard 320kbps",
        "playback_speed" to "Speed",
        "volume" to "Volume",
        "streaming_direct" to "Direct Stream",
        "playing_offline" to "Playing from Offline Cache",

        // Newly added music / Home
        "newly_added_title" to "Newly Added Music",
        "new_albums_title" to "Newest Albums",
        "new_songs_title" to "Recently Added Tracks",
        "new_badge" to "NEW",
        "btn_play_all" to "Play All",
        "btn_shuffle_all" to "Shuffle",
        "see_all" to "See All",

        // Listening Statistics
        "stats_title" to "Listening Statistics",
        "stats_desc" to "Track your listening habits, peak days, hours, and favorite artists",
        "stats_btn_view" to "View Usage Statistics",
        "stats_total_listening" to "Total Listening Time",
        "stats_today" to "Today",
        "stats_this_week" to "This Week",
        "stats_tracks_played" to "Tracks Played",
        "stats_peak_day" to "Peak Listening Day",
        "stats_peak_hours" to "Peak Listening Hours",
        "stats_day_breakdown" to "Activity by Day of Week",
        "stats_time_breakdown" to "Activity by Time of Day",
        "stats_top_artists" to "Top Artists",
        "stats_top_tracks" to "Most Played Songs",
        "stats_empty_title" to "No Listening History Yet",
        "stats_empty_desc" to "Play some music from your server to start building your listening profile!",
        "stats_clear" to "Reset Statistics",
        "stats_clear_confirm" to "Are you sure you want to clear your listening history?",

        // Lyrics
        "lyrics_title" to "Lyrics",
        "lyrics_loading" to "Fetching lyrics...",
        "lyrics_source_label" to "Source:",
        "lyrics_source_file" to "Embedded in File",
        "lyrics_source_server" to "Navidrome Server",
        "lyrics_source_online" to "Online (LrcLib Synced)",
        "lyrics_not_found" to "No lyrics available for this track",
        "lyrics_not_found_desc" to "We checked the audio file, Navidrome server, and online synchronized database.",
        "lyrics_tap_to_seek" to "Tap any lyric line to jump to that moment",
        "lyrics_reload" to "Refetch Lyrics",
        "lyrics_tab_artwork" to "Cover Art",
        "lyrics_tab_lyrics" to "Lyrics"
    )

    private val albanianStrings = mapOf(
        // Tabs
        "tab_library" to "Biblioteka",
        "tab_home" to "Biblioteka",
        "tab_playlists" to "Listat",
        "tab_search" to "Kërko",
        "tab_offline" to "Offline",
        "tab_downloads" to "Offline",
        "tab_settings" to "Cilësimet",

        // Subtabs
        "subtab_libraries" to "Bibliotekat",
        "subtab_songs" to "Këngët",
        "subtab_albums" to "Albumet",
        "subtab_artists" to "Artistët",
        "subtab_quick_mix" to "Miksi i serverit",
        "subtab_recent" to "Të fundit",
        "recently_played_title" to "Të luajtura së fundmi",
        "recently_played_subtitle" to "Këngët që keni dëgjuar së fundmi",
        "empty_recent_title" to "Asnjë këngë e fundit",
        "empty_recent_desc" to "Këngët që luani do të shfaqen këtu për qasje të shpejtë.",
        "server_libraries_title" to "Bibliotekat e serverit Navidrome",
        "server_libraries_desc" to "Shfleto dosjet dhe bibliotekat e veçanta muzikore të konfiguruara në serverin tënd Navidrome.",
        "btn_browse_library" to "Shfleto bibliotekën",
        "active_library_badge" to "BIBLIOTEKA AKTIVE",
        "all_libraries_title" to "Të gjitha dosjet e muzikës",
        "all_libraries_desc" to "Koleksion i përbashkët nga të gjitha dosjet e konfiguruara të serverit",
        "switch_library_prompt" to "Biblioteka aktive",
        "sidebar_libraries_title" to "Bibliotekat e serverit",
        "sidebar_open" to "Bibliotekat",
        "sort_by" to "Rendit sipas",
        "sort_name" to "Emri (A-Z)",
        "sort_duration" to "Kohëzgjatja",
        "sort_recent" to "Shtuar së fundi",
        "sort_artist" to "Artisti",
        "shake_detected_toast" to "Lëkundje e zbuluar! Po luhet këngë e rastësishme nga %s",

        // Deck Actions & General Actions
        "deck_liked" to "Këngët e pëlqyera",
        "deck_liked_sub" to "Të preferuarat e tua",
        "deck_mix" to "Miks i rastësishëm",
        "deck_mix_sub" to "25 këngë të përzgjedhura",
        "deck_shuffle" to "Përziej të gjitha",
        "deck_shuffle_sub" to "Luaj tërë bibliotekën",
        "deck_discover" to "Zbulo",
        "deck_discover_sub" to "Eksploro muzikë të re",
        "play_all" to "Luaj të gjitha",
        "shuffle_all" to "Përziej të gjitha",
        "play_cached" to "Luaj të shkarkuarat",
        "clear_all_cache" to "Pastro memorien",
        "offline_only" to "Vetëm pa internet",
        "sync_now" to "Sinkronizo tani",
        "saved_servers" to "Serverat e ruajtur",
        "tracks_count" to "këngë",
        "settings_crossfade" to "Tranzicioni i zërit (Crossfade)",
        "settings_crossfade_duration" to "Kohëzgjatja e Crossfade",
        "settings_crossfade_seconds" to "Sekonda (1 - 20s)",
        "settings_crossfade_desc" to "Tranzicion i butë midis këngëve të njëpasnjëshme.",
        "multi_libraries_selected" to "%d Biblioteka të zgjedhura",
        "select_all_libraries" to "Zgjidh të gjitha",
        "clear_library_selection" to "Pastro zgjedhjen",
        "all_libraries_combined" to "Të gjitha bibliotekat (E bashkuar)",
        "downloads_title" to "Këngët e Shkarkuara",
        "empty_downloads" to "Nuk ka këngë të shkarkuara",
        "empty_downloads_desc" to "Këngët e shkarkuara do të shfaqen këtu për dëgjim pa internet.",

        // Library & Empty State
        "empty_library_title" to "Nuk u gjet asnjë muzikë",
        "empty_library_desc" to "Lidhu me serverin tënd Navidrome ose skano rrjetin lokal te Cilësimet për të ngarkuar muzikën tënde.",
        "btn_connect_server" to "Konfiguro serverin",
        "btn_scan_network" to "Skano rrjetin automatikisht",
        "album_tracks_count" to "%d këngë",
        "album_duration" to "%d min",
        "btn_play_all" to "Luaj të gjitha",
        "btn_shuffle" to "Përziej",
        "btn_download_all" to "Shkarko të gjitha",
        "badge_offline" to "PA INTERNET",
        "badge_online" to "ONLINE",
        "top_picks" to "Albumet kryesore",
        "featured_artists" to "Artistët",

        // Search
        "search_hint" to "Kërko këngë, albume, artistë...",
        "search_tracks" to "Këngët",
        "search_albums" to "Albumet",
        "search_artists" to "Artistët",
        "search_no_results" to "Nuk u gjet asnjë rezultat për \"%s\"",
        "search_recent" to "Kërko shpejt në serverin tënd Navidrome",
        "search_hint_sub" to "Shkruaj emrin e artistit, albumit ose këngës",
        "search_history_title" to "Kërkimet e fundit",
        "search_history_clear" to "Pastro të gjitha",

        // Playlists
        "playlists_title" to "Listat e këngëve",
        "btn_create_playlist" to "Listë e re",
        "dialog_create_playlist" to "Krijo listë të re",
        "dialog_playlist_name" to "Emri i listës",
        "btn_create" to "Krijo",
        "btn_cancel" to "Anulo",
        "empty_playlists" to "Nuk ka asnjë listë këngësh",
        "empty_playlists_desc" to "Krijo lista vetjake ose sinkronizo ato ekzistuese nga serveri yt Navidrome.",
        "delete_playlist" to "Fshi listën",

        // Offline
        "offline_title" to "Ruajtja pa internet",
        "offline_cached_total" to "Muzikë e shkarkuar",
        "offline_mode_toggle" to "Vetëm pa internet",
        "offline_mode_desc" to "Luaj vetëm këngët e shkarkuara për të kursyer të dhënat celulare",
        "btn_play_cached" to "Luaj të shkarkuarat",
        "btn_clear_cache" to "Pastro memorien",
        "empty_cache_title" to "Nuk ka këngë të shkarkuara",
        "empty_cache_desc" to "Shkarko çdo këngë ose album të plotë për t'i dëgjuar pa lidhje interneti.",

        // Settings
        "settings_title" to "Cilësimet",
        "server_status_title" to "Gjendja e serverit",
        "server_connected" to "I lidhur",
        "server_disconnected" to "I shkëputur",
        "server_sync_now" to "Sinkronizo bibliotekën",
        "server_config_title" to "Serveri Navidrome",
        "protocol" to "Protokolli",
        "host" to "Adresa / IP",
        "host_placeholder" to "192.168.1.50 ose music.server.com",
        "port" to "Porta (E parazgjedhur 4533)",
        "port_placeholder" to "4533",
        "username" to "Emri i përdoruesit",
        "password" to "Fjalëkalimi",
        "use_token_auth" to "Autentikim me Token (MD5/Salt)",
        "use_token_auth_desc" to "E rekomanduar për sigurinë e Navidrome & Subsonic",
        "btn_connect" to "Lidhu me serverin",
        "btn_connecting" to "Duke u lidhur...",
        "btn_auto_scan" to "Skano rrjetin lokal automatikisht",
        "btn_stop_auto_scan" to "Ndalo Skanimin",
        "btn_scanning" to "Duke skanuar rrjetin për Navidrome...",
        "scan_no_network_title" to "Nuk ka lidhje me rrjet",
        "scan_no_network_desc" to "Pajisja është offline. Lidhuni me Wi-Fi ose me një rrjet lokal për të skanuar për servera Navidrome.",
        "library_filter" to "Filtro bibliotekën",
        "all_libraries" to "Të gjitha bibliotekat",
        "select_folder" to "Zgjidh dosjen e muzikës",

        // Appearance & Language
        "appearance_title" to "Pamja & Gjuha",
        "theme_mode" to "Tema e aplikacionit",
        "theme_dark" to "Modaliteti i errët",
        "theme_light" to "Modaliteti i çelët",
        "theme_system" to "Sipas sistemit",
        "language" to "Gjuha",
        "lang_english" to "English (Anglisht)",
        "lang_albanian" to "Shqip",

        // Player & Queue
        "now_playing" to "Po luhet tani",
        "up_next" to "Në radhë",
        "queue_title" to "Radha e këngëve",
        "play_next" to "Luaj më pas",
        "add_to_queue" to "Shto në radhë",
        "quality_hi_res" to "FLAC / Pa humbje",
        "quality_standard" to "Standard 320kbps",
        "playback_speed" to "Shpejtësia",
        "volume" to "Volumi",
        "streaming_direct" to "Transmetim i drejtpërdrejtë",
        "playing_offline" to "Po luhet nga memoria lokale",

        // Newly added music / Home
        "newly_added_title" to "Muzika e shtuar së fundi",
        "new_albums_title" to "Albumet më të reja",
        "new_songs_title" to "Këngët e reja",
        "new_badge" to "E RE",
        "btn_play_all" to "Luaj të gjitha",
        "btn_shuffle_all" to "Përziej",
        "see_all" to "Shiko të gjitha",

        // Listening Statistics
        "stats_title" to "Statistikat e dëgjimit",
        "stats_desc" to "Mëso zakonet e dëgjimit, ditët dhe orët më aktive, si dhe artistët e preferuar",
        "stats_btn_view" to "Shiko statistikat e përdorimit",
        "stats_total_listening" to "Koha totale e dëgjimit",
        "stats_today" to "Sot",
        "stats_this_week" to "Këtë javë",
        "stats_tracks_played" to "Këngë të dëgjuara",
        "stats_peak_day" to "Dita me më shumë dëgjim",
        "stats_peak_hours" to "Orët më aktive",
        "stats_day_breakdown" to "Aktiviteti sipas ditëve të javës",
        "stats_time_breakdown" to "Aktiviteti sipas orarit të ditës",
        "stats_top_artists" to "Artistët më të dëgjuar",
        "stats_top_tracks" to "Këngët më të luajtura",
        "stats_empty_title" to "Ende nuk ka histori dëgjimi",
        "stats_empty_desc" to "Luaj muzikë nga serveri yt për të ndërtuar profilin e statistikave!",
        "stats_clear" to "Pastro statistikat",
        "stats_clear_confirm" to "A je i sigurt që dëshiron të fshish historinë e dëgjimit?",

        // Lyrics
        "lyrics_title" to "Teksti i këngës",
        "lyrics_loading" to "Duke kërkuar tekstin...",
        "lyrics_source_label" to "Burimi:",
        "lyrics_source_file" to "Brenda skedarit",
        "lyrics_source_server" to "Serveri Navidrome",
        "lyrics_source_online" to "Nga Interneti (LrcLib sinkronizuar)",
        "lyrics_not_found" to "Nuk u gjet tekst për këtë këngë",
        "lyrics_not_found_desc" to "U kontrollua skedari audio, serveri Navidrome dhe baza e sinkronizuar online.",
        "lyrics_tap_to_seek" to "Prek çdo rresht për të kërcyer në atë moment",
        "lyrics_reload" to "Rikërko tekstin",
        "lyrics_tab_artwork" to "Kopertina",
        "lyrics_tab_lyrics" to "Teksti"
    )
}
