package com.labix.navirom.ui

enum class AppLanguage(val code: String, val displayName: String, val nativeName: String) {
    ALBANIAN("sq", "Albanian", "Shqip"),
    ENGLISH("en", "English", "English"),
    GERMAN("de", "German", "Deutsch")
}

enum class AppThemeMode(val titleEn: String, val titleSq: String, val titleDe: String = "Systemstandard") {
    DARK("Dark", "I errët", "Dunkel"),
    LIGHT("Light", "I çelët", "Hell"),
    SYSTEM("System Default", "Sipas sistemit", "Systemstandard")
}

object NaviromStrings {

    fun get(key: String, language: AppLanguage = AppLanguage.ALBANIAN): String {
        val map = when (language) {
            AppLanguage.GERMAN -> germanStrings
            AppLanguage.ALBANIAN -> albanianStrings
            AppLanguage.ENGLISH -> englishStrings
        }
        return map[key] ?: englishStrings[key] ?: formatFallbackKey(key)
    }

    private fun formatFallbackKey(key: String): String {
        if (!key.contains("_")) return key
        return key.split("_")
            .filter { it.isNotBlank() }
            .joinToString(" ") { word ->
                word.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
            }
            .ifBlank { key }
    }

    private val englishStrings = mapOf(
        // Greetings
        "greeting_morning" to "Good morning",
        "greeting_afternoon" to "Good afternoon",
        "greeting_evening" to "Good evening",
        "greeting_night" to "Good night",
        "greeting_subtitle" to "What would you like to listen to today?",
        "profile_default_name" to "Music Lover",

        // Tabs
        "tab_library" to "Library",
        "tab_home" to "Library",
        "tab_playlists" to "Playlists",
        "tab_folders" to "Music",
        "tab_music" to "Music",
        "tab_search" to "Search",
        "tab_offline" to "Offline",
        "tab_downloads" to "Offline",
        "tab_settings" to "Settings",

        // Folder View
        "folders_title" to "Music",
        "folders_subtitle" to "Folder View",
        "folders_root_music" to "Music Directory",
        "folders_play_all" to "Play All",
        "folders_shuffle" to "Shuffle",
        "folders_rescan" to "Rescan Storage",
        "folders_scanning" to "Scanning storage...",
        "folders_subfolders" to "Folders",
        "folders_tracks" to "Tracks",
        "folders_empty_title" to "Music Folder is Empty",
        "folders_empty_desc" to "No audio files found in your Music directory. Place MP3, FLAC, or M4A music files into the 'Music' folder on your device.",
        "folders_other_detected" to "Other Music Folders Found on Device",
        "folders_search_hint" to "Search folders and tracks...",
        "folders_up" to "Up one level",
        "folders_file_info" to "File Details",
        "folders_path" to "Path",
        "folders_format" to "Format",
        "folders_size" to "Size",
        "folders_duration" to "Duration",

        // Permissions & Initial Setup
        "perm_welcome_title" to "Welcome to Zana",
        "perm_welcome_subtitle" to "To provide the best music listening experience, Zana requires a couple of standard device permissions.",
        "perm_audio_title" to "Music & Audio Files",
        "perm_audio_desc" to "Allows Zana to scan your Music folder and play local MP3, FLAC, and M4A audio files directly on your device.",
        "perm_audio_status_granted" to "Access Granted",
        "perm_audio_status_required" to "Required for local songs",
        "perm_notif_title" to "Playback Notifications",
        "perm_notif_desc" to "Displays lock-screen playback controls, album artwork, and song controls while music plays in the background.",
        "perm_notif_status_granted" to "Enabled",
        "perm_notif_status_recommended" to "Recommended",
        "perm_btn_grant" to "Grant Permissions",
        "perm_btn_continue" to "Continue to App Tour",
        "perm_btn_skip" to "Skip for Now",
        "perm_all_granted_banner" to "All necessary permissions have been granted!",

        // Onboarding Tour
        "onboard_skip" to "Skip",
        "onboard_next" to "Next",
        "onboard_get_started" to "Get Started",
        "onboard_tour_title" to "Explore What Zana Can Do",
        "onboard_slide1_title" to "Dual Library: Cloud & Local",
        "onboard_slide1_subtitle" to "Stream or Play Offline",
        "onboard_slide1_desc" to "Connect directly to your Navidrome, Subsonic, or compatible server, and explore your device's Music folders in the new native Folder View.",
        "onboard_slide1_feat1" to "Stream Navidrome & Subsonic libraries",
        "onboard_slide1_feat2" to "Native Music folder browsing & breadcrumbs",
        "onboard_slide1_feat3" to "High-speed offline caching for trips",
        "onboard_slide2_title" to "Audiophile Sound & Effects",
        "onboard_slide2_subtitle" to "Warm & Immersive Audio",
        "onboard_slide2_desc" to "Elevate your listening session with smooth gapless crossfades and customizable nostalgic vinyl warmth.",
        "onboard_slide2_feat1" to "Gapless playback & adjustable crossfade",
        "onboard_slide2_feat2" to "Authentic vinyl needle & warm crackle effect",
        "onboard_slide2_feat3" to "Smart sleep timer with auto-disconnect",
        "onboard_slide3_title" to "Synchronized Lyrics & Playlists",
        "onboard_slide3_subtitle" to "Sing Along in Real Time",
        "onboard_slide3_desc" to "Follow synchronized karaoke-style lyrics powered by LRCLIB and TeksteShqip, and build personalized playlists on the fly.",
        "onboard_slide3_feat1" to "Real-time scrolling synchronized lyrics",
        "onboard_slide3_feat2" to "Create and curate customized playlists",
        "onboard_slide3_feat3" to "Instant search across songs, artists & albums",
        "onboard_slide4_title" to "Gestures & Responsive Design",
        "onboard_slide4_subtitle" to "Intuitive & Effortless",
        "onboard_slide4_desc" to "Reorder your queue with drag-and-drop, shake your phone for 2 seconds to shuffle your library, and enjoy adaptive layouts on any screen.",
        "onboard_slide4_feat1" to "Shake-to-Shuffle quick mix playback",
        "onboard_slide4_feat2" to "Fluid drag-and-drop queue management",
        "onboard_slide4_feat3" to "Full tablet, foldable & landscape adaptation",

        // Subtabs & Sections
        "subtab_overview" to "Overview",
        "subtab_libraries" to "Libraries",
        "subtab_local_folders" to "Local Files",
        "subtab_songs" to "Songs",
        "subtab_albums" to "Albums",
        "subtab_artists" to "Artists",
        "subtab_quick_mix" to "Server Mix",
        "subtab_recent" to "Recent",
        "library_labels_title" to "Library Labels",
        "recently_played_title" to "Recently Played",
        "recently_played_subtitle" to "Your recently played tracks",
        "recently_added_title" to "Recently Added",
        "recently_added_subtitle" to "Newest additions to your collection",
        "most_played_title" to "Most Played",
        "most_played_subtitle" to "Your top played albums and tracks",
        "random_albums_title" to "Random from Library",
        "random_albums_subtitle" to "Rediscover hidden gems from your collection",
        "btn_refresh_random" to "Shuffle Random",
        "empty_recent_title" to "No Recent Songs",
        "empty_recent_desc" to "Songs you play will appear here for quick access.",
        "server_libraries_title" to "Navidrome Server Libraries",
        "server_libraries_desc" to "Browse distinct music folders and libraries configured on your Navidrome server.",
        "btn_browse_library" to "Browse Library",
        "active_library_badge" to "ACTIVE LIBRARY",
        "all_libraries_title" to "All Music Folders",
        "all_libraries_desc" to "Combined collection from all configured server folders",
        "switch_library_prompt" to "Active Library",
        "sidebar_libraries_title" to "Server Libraries",
        "sidebar_open" to "Libraries",
        "sort_by" to "Sort by",
        "sort_name" to "Name (A-Z)",
        "sort_duration" to "Duration",
        "sort_recent" to "Recently Added",
        "sort_artist" to "Artist",
        "shake_detected_toast" to "Shake detected! Playing random track from %s",

        // Deck Actions & General Actions
        "deck_liked" to "Liked Songs",
        "deck_liked_sub" to "Your favorites",
        "deck_mix" to "Random Mix",
        "deck_mix_sub" to "25 random songs",
        "deck_shuffle" to "Shuffle All",
        "deck_shuffle_sub" to "Play entire library",
        "deck_discover" to "Discover",
        "deck_discover_sub" to "Explore new music",
        "play_all" to "Play All",
        "shuffle_all" to "Shuffle All",
        "play_cached" to "Play Downloaded",
        "clear_all_cache" to "Clear Cache",
        "offline_only" to "Offline Only",
        "sync_now" to "Sync Now",
        "saved_servers" to "Saved Servers",
        "tracks_count" to "tracks",
        "settings_crossfade" to "Audio Crossfade",
        "settings_crossfade_duration" to "Crossfade Duration",
        "settings_crossfade_seconds" to "Seconds (1 - 20s)",
        "settings_crossfade_desc" to "Smoothly crossfade between consecutive tracks.",
        "settings_vinyl_effect" to "Vinyl Record Animation",
        "settings_vinyl_effect_desc" to "Rotate album artwork like a vinyl record during playback.",
        "press_back_again_to_exit" to "Press back again to exit",
        "exit_dialog_title" to "Exit Navirom?",
        "exit_dialog_desc" to "Are you sure you want to close the application?",
        "exit_dialog_confirm" to "Exit App",
        "exit_dialog_cancel" to "Cancel",
        "multi_libraries_selected" to "%d Libraries Selected",
        "select_all_libraries" to "Select All Libraries",
        "clear_library_selection" to "Clear Selection",
        "all_libraries_combined" to "All Libraries (Unified)",
        "downloads_title" to "Offline Downloads",
        "empty_downloads" to "No Downloaded Tracks",
        "empty_downloads_desc" to "Downloaded tracks will appear here for offline listening.",

        // Library & Empty State
        "empty_library_title" to "No Music Found",
        "empty_library_desc" to "Connect to your Navidrome server or auto-scan your local network in Settings to load your music library.",
        "btn_connect_server" to "Configure Server",
        "btn_scan_network" to "Auto-scan Network",
        "album_tracks_count" to "%d tracks",
        "album_duration" to "%d min",
        "btn_play_all" to "Play All",
        "btn_shuffle" to "Shuffle",
        "btn_download_all" to "Download All",
        "badge_offline" to "OFFLINE",
        "badge_online" to "ONLINE",
        "top_picks" to "Top Albums",
        "featured_artists" to "Artists",

        // Search
        "search_hint" to "Search songs, albums, artists...",
        "search_tracks" to "Songs",
        "search_albums" to "Albums",
        "search_artists" to "Artists",
        "search_no_results" to "No results found for \"%s\"",
        "search_recent" to "Explore your Navidrome server with instant search",
        "search_hint_sub" to "Type artist, album name, or track title",
        "search_history_title" to "Recent Searches",
        "search_history_clear" to "Clear all",

        // Playlists
        "playlists_title" to "Playlists",
        "btn_create_playlist" to "New Playlist",
        "dialog_create_playlist" to "Create New Playlist",
        "dialog_playlist_name" to "Playlist Name",
        "btn_create" to "Create",
        "btn_cancel" to "Cancel",
        "empty_playlists" to "No playlists found",
        "empty_playlists_desc" to "Create custom playlists or sync existing ones from your Navidrome server.",
        "delete_playlist" to "Delete Playlist",

        // Offline
        "offline_title" to "Offline Cache",
        "offline_cached_total" to "Downloaded Music",
        "offline_mode_toggle" to "Offline Only Mode",
        "offline_mode_desc" to "Only play downloaded songs and prevent cellular data usage",
        "btn_play_cached" to "Play Cached Tracks",
        "btn_clear_cache" to "Clear Cache",
        "empty_cache_title" to "No Downloaded Tracks",
        "empty_cache_desc" to "Download any song or full album to listen without an internet connection.",

        // Settings
        "settings_title" to "Settings",
        "server_status_title" to "Server Status",
        "server_connected" to "Connected",
        "server_disconnected" to "Disconnected",
        "server_sync_now" to "Sync Library",
        "server_config_title" to "Navidrome Server",
        "protocol" to "Protocol",
        "host" to "Host / IP Address",
        "host_placeholder" to "192.168.1.50 or music.server.com",
        "port" to "Port (Default 4533)",
        "port_placeholder" to "4533",
        "username" to "Username",
        "password" to "Password",
        "use_token_auth" to "Token Authentication (MD5/Salt)",
        "use_token_auth_desc" to "Recommended for Navidrome & Subsonic security",
        "btn_connect" to "Connect to Server",
        "btn_connecting" to "Connecting...",
        "btn_auto_scan" to "Auto-scan local network",
        "btn_stop_auto_scan" to "Stop Auto-Scan",
        "btn_scanning" to "Scanning subnet for Navidrome...",
        "scan_no_network_title" to "No Network Connection",
        "scan_no_network_desc" to "Device is offline. Connect to Wi-Fi or a local network to auto-scan for Navidrome servers.",
        "library_filter" to "Library Filter",
        "all_libraries" to "All Libraries",
        "select_folder" to "Select Music Folder",

        // Appearance & Language
        "appearance_title" to "Appearance & Language",
        "theme_mode" to "Theme Mode",
        "theme_dark" to "Dark Mode",
        "theme_light" to "Light Mode",
        "theme_system" to "System Default",
        "language" to "Language",
        "lang_english" to "English",
        "lang_albanian" to "Shqip (Albanian)",

        // Player & Queue
        "now_playing" to "Now Playing",
        "up_next" to "Up Next",
        "queue_title" to "Queue",
        "play_next" to "Play Next",
        "add_to_queue" to "Add to Queue",
        "quality_hi_res" to "FLAC / Lossless",
        "quality_standard" to "Standard 320kbps",
        "playback_speed" to "Speed",
        "volume" to "Volume",
        "streaming_direct" to "Direct Stream",
        "playing_offline" to "Playing from Offline Cache",

        // Newly added music / Home
        "newly_added_title" to "Newly Added Music",
        "new_albums_title" to "Newest Albums",
        "new_songs_title" to "Recently Added Tracks",
        "new_badge" to "NEW",
        "btn_play_all" to "Play All",
        "btn_shuffle_all" to "Shuffle",
        "see_all" to "See All",

        // Listening Statistics
        "stats_title" to "Listening Statistics",
        "stats_desc" to "Track your listening habits, peak days, hours, and favorite artists",
        "stats_btn_view" to "View Usage Statistics",
        "stats_total_listening" to "Total Listening Time",
        "stats_today" to "Today",
        "stats_this_week" to "This Week",
        "stats_tracks_played" to "Tracks Played",
        "stats_peak_day" to "Peak Listening Day",
        "stats_peak_hours" to "Peak Listening Hours",
        "stats_day_breakdown" to "Activity by Day of Week",
        "stats_time_breakdown" to "Activity by Time of Day",
        "stats_top_artists" to "Top Artists",
        "stats_top_tracks" to "Most Played Songs",
        "stats_empty_title" to "No Listening History Yet",
        "stats_empty_desc" to "Play some music from your server to start building your listening profile!",
        "stats_clear" to "Reset Statistics",
        "stats_clear_confirm" to "Are you sure you want to clear your listening history?",

        // Lyrics
        "lyrics_title" to "Lyrics",
        "lyrics_loading" to "Fetching lyrics...",
        "lyrics_source_label" to "Source:",
        "lyrics_source_file" to "Embedded in File",
        "lyrics_source_server" to "Navidrome Server",
        "lyrics_source_online" to "Online (LrcLib Synced)",
        "lyrics_source_teksteshqip" to "Online (TeksteShqip)",
        "lyrics_teksteshqip_btn" to "TeksteShqip",
        "lyrics_teksteshqip_dialog_title" to "TeksteShqip Lyrics",
        "lyrics_teksteshqip_desc" to "Enter a TeksteShqip song URL or search for Albanian lyrics",
        "lyrics_teksteshqip_url_hint" to "https://teksteshqip.com/artist/teksti/id",
        "lyrics_teksteshqip_fetch" to "Fetch Lyrics",
        "lyrics_teksteshqip_search_auto" to "Auto-Search TeksteShqip",
        "lyrics_not_found" to "No lyrics available for this track",
        "lyrics_not_found_desc" to "We checked the audio file, Navidrome server, online synchronized database (LrcLib), and TeksteShqip.",
        "lyrics_tap_to_seek" to "Tap any lyric line to jump to that moment",
        "lyrics_reload" to "Refetch Lyrics",
        "lyrics_tab_artwork" to "Cover Art",
        "lyrics_tab_lyrics" to "Lyrics",

        // App Updates
        "updates_section_title" to "App Updates & GitHub Releases",
        "updates_current_version" to "Installed Version",
        "updates_check_btn" to "Check for Updates",
        "updates_checking" to "Checking GitHub releases...",
        "updates_auto_check" to "Check for updates on launch",
        "updates_auto_check_desc" to "Automatically notifies when a new APK is released on GitHub",
        "updates_new_available_title" to "New Update Available!",
        "updates_uptodate_title" to "App is Up to Date",
        "updates_uptodate_desc" to "You are running the latest version available on GitHub.",
        "updates_install_btn" to "Download & Install",
        "updates_downloading" to "Downloading APK...",
        "updates_ready_install" to "Ready to install",
        "updates_changelog" to "What's New",
        "updates_view_on_github" to "View Release on GitHub",
        "updates_github_repo" to "GitHub Repository",
        "updates_dismiss" to "Later",
        "updates_update_now" to "Update Now",
        "updates_never_checked" to "Never checked",
        "updates_server_build" to "Server Build",
        "updates_reinstall_btn" to "Install from Server",
        "updates_last_checked" to "Last checked",
        "updates_published" to "Uploaded",
        "updates_ready_to_install_title" to "Update Ready to Install",
        "updates_install_now_btn" to "Install Now",
        "updates_error_title" to "Update Check Error",
        "updates_retry_btn" to "Retry",
        "updates_repo_hint" to "Enter owner/repo or paste GitHub URL",
        "updates_up_to_date_badge" to "Up to date",
        "updates_installing" to "Installing update...",
        "updates_preparing_installer" to "Launching package installer...",
        "updates_installed_badge" to "Latest Version Installed",

        // Sleep Timer
        "sleep_timer" to "Sleep Timer",
        "sleep_timer_desc" to "Select time before playback pauses:",
        "sleep_timer_custom_min" to "Custom minutes",
        "sleep_timer_set_custom" to "Set Custom Timer",
        "sleep_timer_turn_off" to "Turn off Sleep Timer",
        "sleep_timer_extra_actions" to "Actions on timer end:",
        "sleep_timer_disable_bluetooth" to "Turn off Bluetooth",
        "sleep_timer_disable_bluetooth_desc" to "Disconnects Bluetooth audio devices",
        "sleep_timer_disable_wifi" to "Turn off Wi-Fi",
        "sleep_timer_disable_wifi_desc" to "Disconnects from Wi-Fi networks",
        "sleep_timer_disable_mobile_data" to "Turn off Mobile Data",
        "sleep_timer_disable_mobile_data_desc" to "Disconnects cellular data connection",
        "sleep_timer_active_badge" to "Timer Active",
        "permission_bluetooth_needed" to "Bluetooth permission is required to turn off Bluetooth devices",

        // Secure Settings & ADB Assistant
        "secure_settings_title" to "Secure Settings & ADB Assistant",
        "secure_settings_badge_granted" to "Permission Granted",
        "secure_settings_badge_missing" to "Permission Required",
        "secure_settings_desc" to "Android 10+ restricts apps from silently toggling Wi-Fi, Bluetooth, and Mobile Data in the background. Granting WRITE_SECURE_SETTINGS or using Root enables automatic background radio shutoff.",
        "secure_settings_root_action" to "Execute on this Device (Root / Shizuku)",
        "secure_settings_root_prompt" to "Do you want to execute the ADB permission grant command on this device via Root/Shizuku?",
        "secure_settings_granting" to "Executing command...",
        "secure_settings_granted_success" to "Permission granted successfully! Background radio toggle is now active.",
        "secure_settings_grant_failed" to "Could not grant automatically. Please run the ADB command or grant Root access.",
        "secure_settings_copy_cmd" to "Copy ADB Command",
        "secure_settings_cmd_copied" to "ADB command copied to clipboard!",
        "secure_settings_open_dev" to "Open Developer Options",
        "secure_settings_open_shizuku" to "Open Shizuku",
        "secure_settings_check_status" to "Check Permission Status",
        "secure_settings_wireless_guide" to "Wireless Debugging / LADB: You can also execute the command without a PC using Wireless Debugging with Shizuku or LADB.",
        "secure_settings_fallback_info" to "Without ADB/Root, the app will conveniently bring up the quick system toggle panel when the timer ends.",
        "updates_highlights" to "Highlights & New Features",
        "updates_view_changelog" to "Changelog & Details",

        // Local Folders
        "local_music_folders_title" to "Local Music Folders",
        "local_music_folders_subtitle" to "Manage on-device folders to include in your library and playback",
        "local_folders_active" to "%d of %d folders active",
        "local_folder_all_active" to "All Local Folders Active",
        "local_folder_deactivated" to "Folder Disabled",
        "local_folder_enable_prompt" to "Enable folder to play songs in library",
        "scan_device_folders" to "Scan Device",
        "rescan_device_folders" to "Rescan",
        "no_local_folders_found" to "No local audio folders found on device",
        "local_folder_play_all" to "Play Folder",
        "local_folder_shuffle" to "Shuffle Folder",
        "select_all_local_folders" to "Select All",
        "deselect_all_local_folders" to "Deselect All",
        "local_folders_header" to "On-Device Audio Folders",
        "local_folders_settings_title" to "Local Audio Folders (Smartphone)",
        "local_folders_settings_desc" to "Select which folders on your phone should be available in the app and sidebar.",
        "local_folders_settings_enabled_count" to "%d of %d folders enabled in app",
        "local_folders_sidebar_info" to "Enabled folders appear in the sidebar for quick playback selection.",
        "no_local_folders_enabled_in_settings" to "No folders enabled in Settings",
        "no_local_folders_sidebar_hint" to "Enable local folders in Settings to choose them here in the sidebar.",
        "btn_open_settings_folders" to "Manage Folders in Settings",

        // Cover Quick Actions Sheet
        "cover_quick_actions_title" to "Track Options",
        "cover_quick_actions_desc" to "Countdown timer, song jump and download",
        "countdown_timer_title" to "Countdown Timer",
        "countdown_timer_active" to "Timer running",
        "countdown_timer_stop" to "Stop Timer",
        "countdown_timer_start" to "Start Timer",
        "countdown_end_of_track" to "End of Song",
        "countdown_more_options" to "More Timer Options",
        "jump_to_time_title" to "Jump to Time",
        "jump_to_time_hint" to "e.g. 1:45 or 90s",
        "jump_to_time_btn" to "Jump",
        "jump_to_time_invalid" to "Please enter a valid time (e.g. 1:30)",
        "jump_quick_rewind" to "-30s",
        "jump_quick_forward" to "+30s",
        "jump_quick_start" to "Start (0:00)",
        "jump_quick_middle" to "Middle (50%)",
        "download_this_song_btn" to "Download This Song",
        "download_this_song_desc" to "Save for offline playback without data usage",
        "download_status_downloaded" to "Song is available offline",
        "download_status_downloading" to "Downloading song...",
        "download_status_redownload" to "Re-download",
        "download_status_failed" to "Download failed - tap to retry",
        "cover_open_lyrics" to "Open Lyrics View"
    )

    private val albanianStrings = mapOf(
        // Greetings
        "greeting_morning" to "Mirëmëngjes",
        "greeting_afternoon" to "Mirëdita",
        "greeting_evening" to "Mirëmbrëma",
        "greeting_night" to "Natën e mirë",
        "greeting_subtitle" to "Çfarë dëshironi të dëgjoni sot?",
        "profile_default_name" to "Adhurues Muzike",

        // Tabs
        "tab_library" to "Biblioteka",
        "tab_home" to "Biblioteka",
        "tab_playlists" to "Listat",
        "tab_folders" to "Muzikë",
        "tab_music" to "Muzikë",
        "tab_search" to "Kërko",
        "tab_offline" to "Offline",
        "tab_downloads" to "Offline",
        "tab_settings" to "Cilësimet",

        // Folder View
        "folders_title" to "Muzikë",
        "folders_subtitle" to "Pamja e Dosjeve",
        "folders_root_music" to "Dosja e Muzikës",
        "folders_play_all" to "Luaj të Gjitha",
        "folders_shuffle" to "Përziej",
        "folders_rescan" to "Rikërko Ruajtjen",
        "folders_scanning" to "Po kërkohet ruajtja...",
        "folders_subfolders" to "Dosjet",
        "folders_tracks" to "Këngët",
        "folders_empty_title" to "Dosja e Muzikës është e Zbrazët",
        "folders_empty_desc" to "Nuk u gjetën skedarë audio në dosjen tuaj të Muzikës. Vendosni skedarë MP3, FLAC ose M4A në dosjen 'Music' në pajisjen tuaj.",
        "folders_other_detected" to "Dosje të Tjera Muzike në Pajisje",
        "folders_search_hint" to "Kërko dosje dhe këngë...",
        "folders_up" to "Një nivel më lart",
        "folders_file_info" to "Detajet e Skedarit",
        "folders_path" to "Shtegu",
        "folders_format" to "Formati",
        "folders_size" to "Madhësia",
        "folders_duration" to "Kohëzgjatja",

        // Permissions & Initial Setup
        "perm_welcome_title" to "Mirësevini në Zana",
        "perm_welcome_subtitle" to "Për t'ju ofruar përvojën më të mirë muzikore, Zana kërkon disa leje standarde të pajisjes.",
        "perm_audio_title" to "Muzika dhe Skedarët Audio",
        "perm_audio_desc" to "Lejon Zana të skanojë dosjen tuaj të Muzikës dhe të luajë skedarët audio lokalë MP3, FLAC dhe M4A direkt në pajisje.",
        "perm_audio_status_granted" to "Qasja u dha",
        "perm_audio_status_required" to "E nevojshme për këngët lokale",
        "perm_notif_title" to "Njoftimet e Luajtjes",
        "perm_notif_desc" to "Shfaq kontrollet e luajtjes në ekranin e kyçjes, kopertinën dhe informacionin e këngës kur muzika luan në sfond.",
        "perm_notif_status_granted" to "Aktivizuar",
        "perm_notif_status_recommended" to "E rekomanduar",
        "perm_btn_grant" to "Jepni Lejet",
        "perm_btn_continue" to "Vazhdo te Prezantimi",
        "perm_btn_skip" to "Kalo për Tani",
        "perm_all_granted_banner" to "Të gjitha lejet e nevojshme u dhanë me sukses!",

        // Onboarding Tour
        "onboard_skip" to "Kalo",
        "onboard_next" to "Tjetra",
        "onboard_get_started" to "Fillo Tani",
        "onboard_tour_title" to "Eksploro Çfarë Mund të Bëjë Zana",
        "onboard_slide1_title" to "Bibliotekë e Dyfishtë: Server & Lokale",
        "onboard_slide1_subtitle" to "Dëgjo në Rrjet ose Pa Internet",
        "onboard_slide1_desc" to "Lidhu direkt me serverin tuaj Navidrome, Subsonic ose të ngjashëm, dhe shfleto dosjet e pajisjes me pamjen e re amtare të Dosjeve.",
        "onboard_slide1_feat1" to "Transmeto nga bibliotekat Navidrome & Subsonic",
        "onboard_slide1_feat2" to "Shfletim nativ i dosjeve të Muzikës",
        "onboard_slide1_feat3" to "Ruajtje e shpejtë offline për udhëtime",
        "onboard_slide2_title" to "Tingull Audiofil & Efekte",
        "onboard_slide2_subtitle" to "Përvojë e Ngrohtë & Zhytëse",
        "onboard_slide2_desc" to "Përmirëso seancën tënde të dëgjimit me kapërcim pa ndërprerje (crossfade) dhe ngrohtësinë nostalgjike të diskut vinil.",
        "onboard_slide2_feat1" to "Luajtje pa ndërprerje & crossfade i rregullueshëm",
        "onboard_slide2_feat2" to "Gjilpërë autentike vinili & efekt kërcitjeje",
        "onboard_slide2_feat3" to "Kohëmatës gjumi inteligjent me shkëputje",
        "onboard_slide3_title" to "Tekste të Sinkronizuara & Listat",
        "onboard_slide3_subtitle" to "Këndo së Bashku në Kohë Reale",
        "onboard_slide3_desc" to "Ndiq tekstet e sinkronizuara karaoke përmes LRCLIB dhe TeksteShqip, dhe krijo listat tuaja të personalizuara.",
        "onboard_slide3_feat1" to "Tekste karaoke të lëvizshme në kohë reale",
        "onboard_slide3_feat2" to "Krijim dhe organizim i listave muzikore",
        "onboard_slide3_feat3" to "Kërkim i menjëhershëm për këngë, artistë e albume",
        "onboard_slide4_title" to "Gjestet & Dizajn i Përshtatshëm",
        "onboard_slide4_subtitle" to "Intuitive & e Thjeshtë",
        "onboard_slide4_desc" to "Riorganizo radhën me tërheqje, shkund telefonin për 2 sekonda për të përzier bibliotekën, dhe shijo pamjen në çdo ekran.",
        "onboard_slide4_feat1" to "Shkunde për të Përzier (Shake-to-Shuffle)",
        "onboard_slide4_feat2" to "Menaxhim i radhës me tërheqje të lehtë",
        "onboard_slide4_feat3" to "Përshtatje e plotë për tabletë dhe telefona",

        // Subtabs & Sections
        "subtab_overview" to "Përmbledhje",
        "subtab_libraries" to "Bibliotekat",
        "subtab_local_folders" to "Skedarët Lokalë",
        "subtab_songs" to "Këngët",
        "subtab_albums" to "Albumet",
        "subtab_artists" to "Artistët",
        "subtab_quick_mix" to "Miksi i serverit",
        "subtab_recent" to "Të fundit",
        "library_labels_title" to "Etiketat e Bibliotekës",
        "recently_played_title" to "Të luajtura së fundmi",
        "recently_played_subtitle" to "Këngët që keni dëgjuar së fundmi",
        "recently_added_title" to "Të shtuara së fundmi",
        "recently_added_subtitle" to "Muzika më e re në koleksion",
        "most_played_title" to "Më të dëgjuarat",
        "most_played_subtitle" to "Albumet dhe këngët tuaja kryesore",
        "random_albums_title" to "Rastësore nga Biblioteka",
        "random_albums_subtitle" to "Zbulo thesare të fshehura nga koleksioni",
        "btn_refresh_random" to "Përziej rastësisht",
        "empty_recent_title" to "Asnjë këngë e fundit",
        "empty_recent_desc" to "Këngët që luani do të shfaqen këtu për qasje të shpejtë.",
        "server_libraries_title" to "Bibliotekat e serverit Navidrome",
        "server_libraries_desc" to "Shfleto dosjet dhe bibliotekat e veçanta muzikore të konfiguruara në serverin tënd Navidrome.",
        "btn_browse_library" to "Shfleto bibliotekën",
        "active_library_badge" to "BIBLIOTEKA AKTIVE",
        "all_libraries_title" to "Të gjitha dosjet e muzikës",
        "all_libraries_desc" to "Koleksion i përbashkët nga të gjitha dosjet e konfiguruara të serverit",
        "switch_library_prompt" to "Biblioteka aktive",
        "sidebar_libraries_title" to "Bibliotekat e serverit",
        "sidebar_open" to "Bibliotekat",
        "sort_by" to "Rendit sipas",
        "sort_name" to "Emri (A-Z)",
        "sort_duration" to "Kohëzgjatja",
        "sort_recent" to "Shtuar së fundi",
        "sort_artist" to "Artisti",
        "shake_detected_toast" to "Lëkundje e zbuluar! Po luhet këngë e rastësishme nga %s",

        // Deck Actions & General Actions
        "deck_liked" to "Këngët e pëlqyera",
        "deck_liked_sub" to "Të preferuarat e tua",
        "deck_mix" to "Miks i rastësishëm",
        "deck_mix_sub" to "25 këngë të përzgjedhura",
        "deck_shuffle" to "Përziej të gjitha",
        "deck_shuffle_sub" to "Luaj tërë bibliotekën",
        "deck_discover" to "Zbulo",
        "deck_discover_sub" to "Eksploro muzikë të re",
        "play_all" to "Luaj të gjitha",
        "shuffle_all" to "Përziej të gjitha",
        "play_cached" to "Luaj të shkarkuarat",
        "clear_all_cache" to "Pastro memorien",
        "offline_only" to "Vetëm pa internet",
        "sync_now" to "Sinkronizo tani",
        "saved_servers" to "Serverat e ruajtur",
        "tracks_count" to "këngë",
        "settings_crossfade" to "Tranzicioni i zërit (Crossfade)",
        "settings_crossfade_duration" to "Kohëzgjatja e Crossfade",
        "settings_crossfade_seconds" to "Sekonda (1 - 20s)",
        "settings_crossfade_desc" to "Tranzicion i butë midis këngëve të njëpasnjëshme.",
        "settings_vinyl_effect" to "Efekti i Pllakës Vinil",
        "settings_vinyl_effect_desc" to "Rrotullo kopertinën e albumit si një pllakë vinili gjatë dëgjimit.",
        "press_back_again_to_exit" to "Shtyp përsëri prapa për të dalë",
        "exit_dialog_title" to "Dil nga Navirom?",
        "exit_dialog_desc" to "Jeni të sigurt që dëshironi të mbyllni aplikacionin?",
        "exit_dialog_confirm" to "Dil nga aplikacioni",
        "exit_dialog_cancel" to "Anulo",
        "multi_libraries_selected" to "%d Biblioteka të zgjedhura",
        "select_all_libraries" to "Zgjidh të gjitha",
        "clear_library_selection" to "Pastro zgjedhjen",
        "all_libraries_combined" to "Të gjitha bibliotekat (E bashkuar)",
        "downloads_title" to "Këngët e Shkarkuara",
        "empty_downloads" to "Nuk ka këngë të shkarkuara",
        "empty_downloads_desc" to "Këngët e shkarkuara do të shfaqen këtu për dëgjim pa internet.",

        // Library & Empty State
        "empty_library_title" to "Nuk u gjet asnjë muzikë",
        "empty_library_desc" to "Lidhu me serverin tënd Navidrome ose skano rrjetin lokal te Cilësimet për të ngarkuar muzikën tënde.",
        "btn_connect_server" to "Konfiguro serverin",
        "btn_scan_network" to "Skano rrjetin automatikisht",
        "album_tracks_count" to "%d këngë",
        "album_duration" to "%d min",
        "btn_play_all" to "Luaj të gjitha",
        "btn_shuffle" to "Përziej",
        "btn_download_all" to "Shkarko të gjitha",
        "badge_offline" to "PA INTERNET",
        "badge_online" to "ONLINE",
        "top_picks" to "Albumet kryesore",
        "featured_artists" to "Artistët",

        // Search
        "search_hint" to "Kërko këngë, albume, artistë...",
        "search_tracks" to "Këngët",
        "search_albums" to "Albumet",
        "search_artists" to "Artistët",
        "search_no_results" to "Nuk u gjet asnjë rezultat për \"%s\"",
        "search_recent" to "Kërko shpejt në serverin tënd Navidrome",
        "search_hint_sub" to "Shkruaj emrin e artistit, albumit ose këngës",
        "search_history_title" to "Kërkimet e fundit",
        "search_history_clear" to "Pastro të gjitha",

        // Playlists
        "playlists_title" to "Listat e këngëve",
        "btn_create_playlist" to "Listë e re",
        "dialog_create_playlist" to "Krijo listë të re",
        "dialog_playlist_name" to "Emri i listës",
        "btn_create" to "Krijo",
        "btn_cancel" to "Anulo",
        "empty_playlists" to "Nuk ka asnjë listë këngësh",
        "empty_playlists_desc" to "Krijo lista vetjake ose sinkronizo ato ekzistuese nga serveri yt Navidrome.",
        "delete_playlist" to "Fshi listën",

        // Offline
        "offline_title" to "Ruajtja pa internet",
        "offline_cached_total" to "Muzikë e shkarkuar",
        "offline_mode_toggle" to "Vetëm pa internet",
        "offline_mode_desc" to "Luaj vetëm këngët e shkarkuara për të kursyer të dhënat celulare",
        "btn_play_cached" to "Luaj të shkarkuarat",
        "btn_clear_cache" to "Pastro memorien",
        "empty_cache_title" to "Nuk ka këngë të shkarkuara",
        "empty_cache_desc" to "Shkarko çdo këngë ose album të plotë për t'i dëgjuar pa lidhje interneti.",

        // Settings
        "settings_title" to "Cilësimet",
        "server_status_title" to "Gjendja e serverit",
        "server_connected" to "I lidhur",
        "server_disconnected" to "I shkëputur",
        "server_sync_now" to "Sinkronizo bibliotekën",
        "server_config_title" to "Serveri Navidrome",
        "protocol" to "Protokolli",
        "host" to "Adresa / IP",
        "host_placeholder" to "192.168.1.50 ose music.server.com",
        "port" to "Porta (E parazgjedhur 4533)",
        "port_placeholder" to "4533",
        "username" to "Emri i përdoruesit",
        "password" to "Fjalëkalimi",
        "use_token_auth" to "Autentikim me Token (MD5/Salt)",
        "use_token_auth_desc" to "E rekomanduar për sigurinë e Navidrome & Subsonic",
        "btn_connect" to "Lidhu me serverin",
        "btn_connecting" to "Duke u lidhur...",
        "btn_auto_scan" to "Skano rrjetin lokal automatikisht",
        "btn_stop_auto_scan" to "Ndalo Skanimin",
        "btn_scanning" to "Duke skanuar rrjetin për Navidrome...",
        "scan_no_network_title" to "Nuk ka lidhje me rrjet",
        "scan_no_network_desc" to "Pajisja është offline. Lidhuni me Wi-Fi ose me një rrjet lokal për të skanuar për servera Navidrome.",
        "library_filter" to "Filtro bibliotekën",
        "all_libraries" to "Të gjitha bibliotekat",
        "select_folder" to "Zgjidh dosjen e muzikës",

        // Appearance & Language
        "appearance_title" to "Pamja & Gjuha",
        "theme_mode" to "Tema e aplikacionit",
        "theme_dark" to "Modaliteti i errët",
        "theme_light" to "Modaliteti i çelët",
        "theme_system" to "Sipas sistemit",
        "language" to "Gjuha",
        "lang_english" to "English (Anglisht)",
        "lang_albanian" to "Shqip",

        // Player & Queue
        "now_playing" to "Po luhet tani",
        "up_next" to "Në radhë",
        "queue_title" to "Radha e këngëve",
        "play_next" to "Luaj më pas",
        "add_to_queue" to "Shto në radhë",
        "quality_hi_res" to "FLAC / Pa humbje",
        "quality_standard" to "Standard 320kbps",
        "playback_speed" to "Shpejtësia",
        "volume" to "Volumi",
        "streaming_direct" to "Transmetim i drejtpërdrejtë",
        "playing_offline" to "Po luhet nga memoria lokale",

        // Newly added music / Home
        "newly_added_title" to "Muzika e shtuar së fundi",
        "new_albums_title" to "Albumet më të reja",
        "new_songs_title" to "Këngët e reja",
        "new_badge" to "E RE",
        "btn_play_all" to "Luaj të gjitha",
        "btn_shuffle_all" to "Përziej",
        "see_all" to "Shiko të gjitha",

        // Listening Statistics
        "stats_title" to "Statistikat e dëgjimit",
        "stats_desc" to "Mëso zakonet e dëgjimit, ditët dhe orët më aktive, si dhe artistët e preferuar",
        "stats_btn_view" to "Shiko statistikat e përdorimit",
        "stats_total_listening" to "Koha totale e dëgjimit",
        "stats_today" to "Sot",
        "stats_this_week" to "Këtë javë",
        "stats_tracks_played" to "Këngë të dëgjuara",
        "stats_peak_day" to "Dita me më shumë dëgjim",
        "stats_peak_hours" to "Orët më aktive",
        "stats_day_breakdown" to "Aktiviteti sipas ditëve të javës",
        "stats_time_breakdown" to "Aktiviteti sipas orarit të ditës",
        "stats_top_artists" to "Artistët më të dëgjuar",
        "stats_top_tracks" to "Këngët më të luajtura",
        "stats_empty_title" to "Ende nuk ka histori dëgjimi",
        "stats_empty_desc" to "Luaj muzikë nga serveri yt për të ndërtuar profilin e statistikave!",
        "stats_clear" to "Pastro statistikat",
        "stats_clear_confirm" to "A je i sigurt që dëshiron të fshish historinë e dëgjimit?",

        // Lyrics
        "lyrics_title" to "Teksti i këngës",
        "lyrics_loading" to "Duke kërkuar tekstin...",
        "lyrics_source_label" to "Burimi:",
        "lyrics_source_file" to "Brenda skedarit",
        "lyrics_source_server" to "Serveri Navidrome",
        "lyrics_source_online" to "Nga Interneti (LrcLib sinkronizuar)",
        "lyrics_source_teksteshqip" to "Nga Interneti (TeksteShqip)",
        "lyrics_teksteshqip_btn" to "TeksteShqip",
        "lyrics_teksteshqip_dialog_title" to "Teksti nga TeksteShqip",
        "lyrics_teksteshqip_desc" to "Vendos linkun nga TeksteShqip ose kërko tekstin shqip",
        "lyrics_teksteshqip_url_hint" to "https://teksteshqip.com/artisti/teksti/id",
        "lyrics_teksteshqip_fetch" to "Merr tekstin",
        "lyrics_teksteshqip_search_auto" to "Kërko automatikisht në TeksteShqip",
        "lyrics_not_found" to "Nuk u gjet tekst për këtë këngë",
        "lyrics_not_found_desc" to "U kontrollua skedari audio, serveri Navidrome, LrcLib dhe TeksteShqip.",
        "lyrics_tap_to_seek" to "Prek çdo rresht për të kërcyer në atë moment",
        "lyrics_reload" to "Rikërko tekstin",
        "lyrics_tab_artwork" to "Kopertina",
        "lyrics_tab_lyrics" to "Teksti",

        // App Updates
        "updates_section_title" to "Përditësimet e Aplikacionit & GitHub",
        "updates_current_version" to "Versioni i instaluar",
        "updates_check_btn" to "Kontrollo për përditësime",
        "updates_checking" to "Duke kontrolluar në GitHub...",
        "updates_auto_check" to "Kontrollo automatikisht në nisje",
        "updates_auto_check_desc" to "Njofton automatikisht kur një APK i ri ngarkohet në GitHub",
        "updates_new_available_title" to "Përditësim i ri në dispozicion!",
        "updates_uptodate_title" to "Aplikacioni është i përditësuar",
        "updates_uptodate_desc" to "Po përdorni versionin më të fundit nga GitHub.",
        "updates_install_btn" to "Shkarko dhe Instalo",
        "updates_downloading" to "Duke shkarkuar APK...",
        "updates_ready_install" to "Gati për instalim",
        "updates_changelog" to "Çfarë ka të re",
        "updates_view_on_github" to "Shiko në GitHub",
        "updates_github_repo" to "Depoja në GitHub",
        "updates_dismiss" to "Më vonë",
        "updates_update_now" to "Përditëso tani",
        "updates_never_checked" to "Pa kontrolluar",
        "updates_server_build" to "Versioni në server",
        "updates_reinstall_btn" to "Instalo nga serveri",
        "updates_last_checked" to "Kontrolluar së fundmi",
        "updates_published" to "Ngarkuar më",
        "updates_ready_to_install_title" to "Përditësimi është gati për instalim",
        "updates_install_now_btn" to "Instalo tani",
        "updates_error_title" to "Gabim gjatë kontrollit",
        "updates_retry_btn" to "Provo përsëri",
        "updates_repo_hint" to "Shkruani pronari/depoja ose vegëzën GitHub",
        "updates_up_to_date_badge" to "I përditësuar",
        "updates_installing" to "Duke instaluar përditësimin...",
        "updates_preparing_installer" to "Duke nisur instaluesin e paketës...",
        "updates_installed_badge" to "Versioni më i fundit i instaluar",

        // Sleep Timer
        "sleep_timer" to "Kohëmatësi i gjumit",
        "sleep_timer_desc" to "Zgjidhni kohën para se të ndalet muzika:",
        "sleep_timer_custom_min" to "Minuta të personalizuara",
        "sleep_timer_set_custom" to "Vendos kohëmatësin",
        "sleep_timer_turn_off" to "Fik kohëmatësin e gjumit",
        "sleep_timer_extra_actions" to "Veprimet kur përfundon koha:",
        "sleep_timer_disable_bluetooth" to "Fik Bluetooth",
        "sleep_timer_disable_bluetooth_desc" to "Shkëput pajisjet audio Bluetooth",
        "sleep_timer_disable_wifi" to "Fik Wi-Fi",
        "sleep_timer_disable_wifi_desc" to "Shkëput lidhjen me rrjetin Wi-Fi",
        "sleep_timer_disable_mobile_data" to "Fik të dhënat celulare",
        "sleep_timer_disable_mobile_data_desc" to "Shkëput internetin e telefonit",
        "sleep_timer_active_badge" to "Kohëmatësi aktiv",
        "permission_bluetooth_needed" to "Kërkohet leja e Bluetooth për të shkëputur pajisjet Bluetooth",

        // Secure Settings & ADB Assistant
        "secure_settings_title" to "Asistenti i lejeve ADB & Secure Settings",
        "secure_settings_badge_granted" to "Leja është aktive",
        "secure_settings_badge_missing" to "Kërkohet leja",
        "secure_settings_desc" to "Nga Android 10+, sistemi kufizon fikjen automatike të Wi-Fi, Bluetooth dhe internetit celular në sfond. Dhënia e lejes WRITE_SECURE_SETTINGS ose Root mundëson fikjen e menjëhershme.",
        "secure_settings_root_action" to "Ekzekuto në këtë pajisje (Root / Shizuku)",
        "secure_settings_root_prompt" to "Dëshironi të ekzekutoni komandën e lejes ADB drejtpërdrejt në këtë pajisje përmes Root/Shizuku?",
        "secure_settings_granting" to "Po ekzekutohet komanda...",
        "secure_settings_granted_success" to "Leja u dha me sukses! Fikja automatike në sfond tani është aktive.",
        "secure_settings_grant_failed" to "Ekzekutimi dështoi. Ju lutemi kontrolloni Root/Shizuku ose përdorni komandën ADB.",
        "secure_settings_copy_cmd" to "Kopjo komandën ADB",
        "secure_settings_cmd_copied" to "Komanda ADB u kopjua në kujtesë!",
        "secure_settings_open_dev" to "Hap opsionet e zhvilluesit",
        "secure_settings_open_shizuku" to "Hap Shizuku",
        "secure_settings_check_status" to "Kontrollo statusin",
        "secure_settings_wireless_guide" to "Wireless Debugging / LADB: Mund ta ekzekutoni komandën pa kompjuter duke përdorur Shizuku ose LADB.",
        "secure_settings_fallback_info" to "Pa ADB/Root, aplikacioni do të shfaqë menynë e shpejtë të sistemit kur mbaron koha.",
        "updates_highlights" to "Të rejat kryesore",
        "updates_view_changelog" to "Regjistri i ndryshimeve",

        // Local Folders
        "local_music_folders_title" to "Dosjet e Muzikës Lokale",
        "local_music_folders_subtitle" to "Menaxhoni dosjet në pajisje për t'i përfshirë në bibliotekë dhe dëgjim",
        "local_folders_active" to "%d nga %d dosje aktive",
        "local_folder_all_active" to "Të gjitha dosjet lokale aktive",
        "local_folder_deactivated" to "Dosja e çaktivizuar",
        "local_folder_enable_prompt" to "Aktivizo dosjen për të luajtur këngë",
        "scan_device_folders" to "Skano pajisjen",
        "rescan_device_folders" to "Risko",
        "no_local_folders_found" to "Nuk u gjetën dosje me muzikë në pajisje",
        "local_folder_play_all" to "Luaj dosjen",
        "local_folder_shuffle" to "Përziej dosjen",
        "select_all_local_folders" to "Zgjidhi të gjitha",
        "deselect_all_local_folders" to "Çzgjidhi të gjitha",
        "local_folders_header" to "Dosjet e Muzikës në Pajisje",
        "local_folders_settings_title" to "Dosjet Lokale të Muzikës (Pajisje)",
        "local_folders_settings_desc" to "Zgjidhni cilat dosje të telefonit të jenë të disponueshme në aplikacion dhe në shiritin anësor.",
        "local_folders_settings_enabled_count" to "%d nga %d dosje të aktivizuara në aplikacion",
        "local_folders_sidebar_info" to "Dosjet e aktivizuara do të shfaqen në shiritin anësor për zgjedhje të shpejtë të luajtjes.",
        "no_local_folders_enabled_in_settings" to "Asnjë dosje e aktivizuar në Cilësime",
        "no_local_folders_sidebar_hint" to "Aktivizoni dosjet lokale në Cilësime që të shfaqen këtu në shiritin anësor.",
        "btn_open_settings_folders" to "Menaxho Dosjet në Cilësime",

        // Cover Quick Actions Sheet
        "cover_quick_actions_title" to "Opsionet e Shpejta",
        "cover_quick_actions_desc" to "Kohëmatësi, kërcimi në kohë dhe shkarkimi",
        "countdown_timer_title" to "Kohëmatësi i Numërimit Mbrapsht",
        "countdown_timer_active" to "Kohëmatësi aktiv",
        "countdown_timer_stop" to "Ndalo Kohëmatësin",
        "countdown_timer_start" to "Fillo Kohëmatësin",
        "countdown_end_of_track" to "Fundi i këngës",
        "countdown_more_options" to "Më shumë opsione të kohëmatësit",
        "jump_to_time_title" to "Kërce në Kohë",
        "jump_to_time_hint" to "psh. 1:45 ose 90s",
        "jump_to_time_btn" to "Kërce",
        "jump_to_time_invalid" to "Ju lutem shkruani një kohë të vlefshme (psh. 1:30)",
        "jump_quick_rewind" to "-30s",
        "jump_quick_forward" to "+30s",
        "jump_quick_start" to "Fillim (0:00)",
        "jump_quick_middle" to "Mes (50%)",
        "download_this_song_btn" to "Shkarko këtë këngë",
        "download_this_song_desc" to "Ruaje për dëgjim pa internet",
        "download_status_downloaded" to "E shkarkuar dhe e gatshme offline",
        "download_status_downloading" to "Duke shkarkuar këngën...",
        "download_status_redownload" to "Rishkarko",
        "download_status_failed" to "Shkarkimi dështoi - prek për të riprovuar",
        "cover_open_lyrics" to "Hap Pamjen e Tekstit"
    )

    private val germanStrings = mapOf(
        // Greetings
        "greeting_morning" to "Guten Morgen",
        "greeting_afternoon" to "Guten Tag",
        "greeting_evening" to "Guten Abend",
        "greeting_night" to "Gute Nacht",
        "greeting_subtitle" to "Was möchtest du heute hören?",
        "profile_default_name" to "Musikliebhaber",

        // Tabs
        "tab_library" to "Bibliothek",
        "tab_home" to "Bibliothek",
        "tab_playlists" to "Playlists",
        "tab_folders" to "Musik",
        "tab_music" to "Musik",
        "tab_search" to "Suche",
        "tab_offline" to "Offline",
        "tab_downloads" to "Offline",
        "tab_settings" to "Einstellungen",

        // Folder View
        "folders_title" to "Musik",
        "folders_subtitle" to "Ordneransicht",
        "folders_root_music" to "Musik-Verzeichnis",
        "folders_play_all" to "Alle abspielen",
        "folders_shuffle" to "Mischen",
        "folders_rescan" to "Speicher neu scannen",
        "folders_scanning" to "Speicher wird gescannt...",
        "folders_subfolders" to "Ordner",
        "folders_tracks" to "Titel",
        "folders_empty_title" to "Musik-Ordner ist leer",
        "folders_empty_desc" to "Keine Audiodateien im Musik-Verzeichnis gefunden. Lege MP3-, FLAC- oder M4A-Dateien in den Ordner 'Music' auf deinem Gerät ab.",
        "folders_other_detected" to "Weitere Musikordner auf dem Gerät",
        "folders_search_hint" to "Ordner und Titel durchsuchen...",
        "folders_up" to "Eine Ebene höher",
        "folders_file_info" to "Dateidetails",
        "folders_path" to "Pfad",
        "folders_format" to "Format",
        "folders_size" to "Größe",
        "folders_duration" to "Dauer",

        // Permissions & Initial Setup
        "perm_welcome_title" to "Willkommen bei Zana",
        "perm_welcome_subtitle" to "Für das beste Musikerlebnis benötigt Zana ein paar standardmäßige Berechtigungen auf deinem Gerät.",
        "perm_audio_title" to "Musik- & Audiodateien",
        "perm_audio_desc" to "Erlaubt Zana, deinen Musikordner zu durchsuchen und lokale MP3-, FLAC- und M4A-Audiodateien direkt abzuspielen.",
        "perm_audio_status_granted" to "Zugriff gewährt",
        "perm_audio_status_required" to "Erforderlich für lokale Titel",
        "perm_notif_title" to "Wiedergabebenachrichtigungen",
        "perm_notif_desc" to "Zeigt Steuerelemente, Album-Cover und Titelinfos auf dem Sperrbildschirm und im Infobereich an.",
        "perm_notif_status_granted" to "Aktiviert",
        "perm_notif_status_recommended" to "Empfohlen",
        "perm_btn_grant" to "Berechtigungen Erteilen",
        "perm_btn_continue" to "Weiter zur App-Tour",
        "perm_btn_skip" to "Jetzt Überspringen",
        "perm_all_granted_banner" to "Alle erforderlichen Berechtigungen wurden erteilt!",

        // Onboarding Tour
        "onboard_skip" to "Überspringen",
        "onboard_next" to "Weiter",
        "onboard_get_started" to "Jetzt Loslegen",
        "onboard_tour_title" to "Entdecke, was Zana kann",
        "onboard_slide1_title" to "Duale Mediathek: Cloud & Lokal",
        "onboard_slide1_subtitle" to "Streamen oder Offline Hören",
        "onboard_slide1_desc" to "Verbinde dich direkt mit deinem Navidrome- oder Subsonic-Server und durchsuche deine Musikordner in der nativen Ordneransicht.",
        "onboard_slide1_feat1" to "Streaming von Navidrome & Subsonic Servern",
        "onboard_slide1_feat2" to "Native Musikordner-Navigation & Breadcrumbs",
        "onboard_slide1_feat3" to "Schneller Offline-Cache für unterwegs",
        "onboard_slide2_title" to "Audiophiler Klang & Effekte",
        "onboard_slide2_subtitle" to "Warmer & Immersiver Klang",
        "onboard_slide2_desc" to "Verfeinere dein Hörerlebnis mit lückenloser Überblendung (Crossfade) und authentischer Vinyl-Nadelwärme.",
        "onboard_slide2_feat1" to "Lückenlose Wiedergabe & anpassbares Crossfade",
        "onboard_slide2_feat2" to "Authentische Vinyl-Nadel & Knistereffekt",
        "onboard_slide2_feat3" to "Smarter Sleep-Timer mit Trennfunktion",
        "onboard_slide3_title" to "Synchrone Songtexte & Playlists",
        "onboard_slide3_subtitle" to "In Echtzeit Mitsingen",
        "onboard_slide3_desc" to "Sing mit synchronisierten Karaoke-Texten via LRCLIB und TeksteShqip mit und erstelle eigene Playlists im Handumdrehen.",
        "onboard_slide3_feat1" to "Echtzeit-synchronisierte Karaoke-Songtexte",
        "onboard_slide3_feat2" to "Eigene Playlists erstellen und kuratieren",
        "onboard_slide3_feat3" to "Sofortsuche nach Titeln, Interpreten & Alben",
        "onboard_slide4_title" to "Gesten & Responsives Design",
        "onboard_slide4_subtitle" to "Intuitiv & Mühelos",
        "onboard_slide4_desc" to "Sortiere deine Warteschlange per Drag-and-Drop, schüttle dein Smartphone für 2 Sekunden zum Mischen und genieße optimierte Layouts.",
        "onboard_slide4_feat1" to "Schütteln zum Mischen (Shake-to-Shuffle)",
        "onboard_slide4_feat2" to "Flüssige Drag-and-Drop-Warteschlange",
        "onboard_slide4_feat3" to "Vollständige Anpassung an Tablets & Foldables",

        // Subtabs & Sections
        "subtab_overview" to "Übersicht",
        "subtab_libraries" to "Bibliotheken",
        "subtab_local_folders" to "Lokale Dateien",
        "subtab_songs" to "Titel",
        "subtab_albums" to "Alben",
        "subtab_artists" to "Künstler",
        "subtab_quick_mix" to "Server Mix",
        "subtab_recent" to "Verlauf",
        "library_labels_title" to "Bibliotheks-Labels",
        "recently_played_title" to "Zuletzt Gespielt",
        "recently_played_subtitle" to "Deine zuletzt gehörten Titel",
        "recently_added_title" to "Kürzlich Hinzugefügt",
        "recently_added_subtitle" to "Neuzugänge in deiner Sammlung",
        "most_played_title" to "Meistgespielt",
        "most_played_subtitle" to "Deine beliebtesten Alben und Titel",
        "random_albums_title" to "Zufällig aus der Mediathek",
        "random_albums_subtitle" to "Entdecke Perlen aus deiner Sammlung wieder",
        "btn_refresh_random" to "Neu Mischen",
        "empty_recent_title" to "Keine letzten Titel",
        "empty_recent_desc" to "Gespielte Titel erscheinen hier für schnellen Zugriff.",
        "server_libraries_title" to "Navidrome Musikordner",
        "server_libraries_desc" to "Durchsuche verschiedene konfigurierte Musikordner auf deinem Navidrome-Server.",
        "btn_browse_library" to "Bibliothek öffnen",
        "active_library_badge" to "AKTIVE BIBLIOTHEK",
        "all_libraries_title" to "Alle Musikordner",
        "all_libraries_desc" to "Kombinierte Sammlung aller Server-Ordner",
        "switch_library_prompt" to "Aktive Bibliothek",
        "sidebar_libraries_title" to "Server-Bibliotheken",
        "sidebar_open" to "Bibliotheken",
        "sort_by" to "Sortieren nach",
        "sort_name" to "Name (A-Z)",
        "sort_duration" to "Dauer",
        "sort_recent" to "Zuletzt hinzugefügt",
        "sort_artist" to "Künstler",
        "shake_detected_toast" to "Schütteln erkannt! Spiele zufälligen Titel aus %s",

        // Deck Actions & General Actions
        "deck_liked" to "Lieblingslieder",
        "deck_liked_sub" to "Deine Favoriten",
        "deck_mix" to "Zufallsmix",
        "deck_mix_sub" to "25 Zufallstitel",
        "deck_shuffle" to "Alles Mischen",
        "deck_shuffle_sub" to "Ganze Bibliothek abspielen",
        "deck_discover" to "Entdecken",
        "deck_discover_sub" to "Neue Musik erkunden",
        "play_all" to "Alle abspielen",
        "shuffle_all" to "Zufällig wiedergeben",
        "play_cached" to "Heruntergeladene abspielen",
        "clear_all_cache" to "Cache leeren",
        "offline_only" to "Nur Offline",
        "sync_now" to "Jetzt synchronisieren",
        "saved_servers" to "Gespeicherte Server",
        "tracks_count" to "Titel",
        "settings_crossfade" to "Audio-Überblendung (Crossfade)",
        "settings_crossfade_duration" to "Überblendungsdauer",
        "settings_crossfade_seconds" to "Sekunden (1 - 20s)",
        "settings_crossfade_desc" to "Nahtloser Übergang zwischen aufeinanderfolgenden Titeln.",
        "settings_vinyl_effect" to "Schallplatten-Effekt (Vinyl)",
        "settings_vinyl_effect_desc" to "Dreht das Album-Cover während der Wiedergabe wie eine Vinyl-Schallplatte.",
        "press_back_again_to_exit" to "Erneut zurück drücken zum Beenden",
        "exit_dialog_title" to "Navirom beenden?",
        "exit_dialog_desc" to "Möchten Sie die Anwendung wirklich schließen?",
        "exit_dialog_confirm" to "App beenden",
        "exit_dialog_cancel" to "Abbrechen",
        "multi_libraries_selected" to "%d Bibliotheken ausgewählt",
        "select_all_libraries" to "Alle auswählen",
        "clear_library_selection" to "Auswahl aufheben",
        "all_libraries_combined" to "Alle Bibliotheken (Vereint)",
        "downloads_title" to "Offline Downloads",
        "empty_downloads" to "Keine Downloads vorhanden",
        "empty_downloads_desc" to "Heruntergeladene Titel erscheinen hier für Offline-Wiedergabe.",

        // Library & Empty State
        "empty_library_title" to "Keine Musik gefunden",
        "empty_library_desc" to "Verbinde dich in den Einstellungen mit deinem Navidrome-Server.",
        "btn_connect_server" to "Server einrichten",
        "btn_scan_network" to "Netzwerk automatisch scannen",
        "album_tracks_count" to "%d Titel",
        "album_duration" to "%d Min",
        "btn_play_all" to "Alle abspielen",
        "btn_shuffle" to "Mischen",
        "btn_download_all" to "Alle herunterladen",
        "badge_offline" to "OFFLINE",
        "badge_online" to "ONLINE",
        "top_picks" to "Top Alben",
        "featured_artists" to "Künstler",

        // Search
        "search_hint" to "Titel, Alben, Künstler suchen...",
        "search_tracks" to "Titel",
        "search_albums" to "Alben",
        "search_artists" to "Künstler",
        "search_no_results" to "Keine Ergebnisse für \"%s\"",
        "search_recent" to "Durchsuche deinen Navidrome-Server",
        "search_hint_sub" to "Gib Künstler, Album oder Titel ein",
        "search_history_title" to "Letzte Suchanfragen",
        "search_history_clear" to "Verlauf löschen",

        // Playlists
        "playlists_title" to "Wiedergabelisten",
        "btn_create_playlist" to "Neue Playlist",
        "dialog_create_playlist" to "Neue Playlist erstellen",
        "dialog_playlist_name" to "Playlist-Name",
        "btn_create" to "Erstellen",
        "btn_cancel" to "Abbrechen",
        "empty_playlists" to "Keine Playlists vorhanden",
        "empty_playlists_desc" to "Erstelle eigene Playlists oder synchronisiere sie vom Server.",
        "delete_playlist" to "Playlist löschen",

        // Offline
        "offline_title" to "Offline-Speicher",
        "offline_cached_total" to "Heruntergeladene Musik",
        "offline_mode_toggle" to "Offline-Modus",
        "offline_mode_desc" to "Nur heruntergeladene Titel abspielen (spart mobile Daten)",
        "btn_play_cached" to "Heruntergeladene abspielen",
        "btn_clear_cache" to "Cache leeren",
        "empty_cache_title" to "Keine Offline-Titel",
        "empty_cache_desc" to "Lade beliebige Titel oder ganze Alben für unterwegs herunter.",

        // Settings
        "settings_title" to "Einstellungen",
        "server_status_title" to "Server-Status",
        "server_connected" to "Verbunden",
        "server_disconnected" to "Getrennt",
        "server_sync_now" to "Bibliothek synchronisieren",
        "server_config_title" to "Navidrome Server",
        "protocol" to "Protokoll",
        "host" to "Host / IP-Adresse",
        "host_placeholder" to "192.168.1.50 oder musik.server.de",
        "port" to "Port (Standard 4533)",
        "port_placeholder" to "4533",
        "username" to "Benutzername",
        "password" to "Passwort",
        "use_token_auth" to "Token-Authentifizierung (MD5/Salt)",
        "use_token_auth_desc" to "Empfohlen für Navidrome & Subsonic Sicherheit",
        "btn_connect" to "Mit Server verbinden",
        "btn_connecting" to "Verbinde...",
        "btn_auto_scan" to "Lokales Netzwerk scannen",
        "btn_stop_auto_scan" to "Scan abbrechen",
        "btn_scanning" to "Suche nach Navidrome im Subnetz...",
        "scan_no_network_title" to "Keine Netzwerkverbindung",
        "scan_no_network_desc" to "Gerät ist offline. Verbinde mit WLAN für Server-Scan.",
        "library_filter" to "Bibliotheksfilter",
        "all_libraries" to "Alle Bibliotheken",
        "select_folder" to "Musikordner wählen",

        // Appearance & Language
        "appearance_title" to "Erscheinungsbild & Sprache",
        "theme_mode" to "Design-Modus",
        "theme_dark" to "Dunkel",
        "theme_light" to "Hell",
        "theme_system" to "Systemstandard",
        "language" to "Sprache",
        "lang_english" to "English (Englisch)",
        "lang_german" to "Deutsch",
        "lang_albanian" to "Shqip (Albanisch)",

        // Player & Queue
        "now_playing" to "Aktuelle Wiedergabe",
        "up_next" to "Als Nächstes",
        "queue_title" to "Warteschlange",
        "play_next" to "Als Nächstes abspielen",
        "add_to_queue" to "An Warteschlange anhängen",
        "quality_hi_res" to "FLAC / Lossless",
        "quality_standard" to "Standard 320kbps",
        "playback_speed" to "Geschwindigkeit",
        "volume" to "Lautstärke",
        "streaming_direct" to "Direkter Stream",
        "playing_offline" to "Aus Offline-Cache",

        // Newly added music / Home
        "newly_added_title" to "Kürzlich Hinzugefügte Musik",
        "new_albums_title" to "Neueste Alben",
        "new_songs_title" to "Neu hinzugefügte Titel",
        "new_badge" to "NEU",
        "btn_play_all" to "Alle abspielen",
        "btn_shuffle_all" to "Mischen",
        "see_all" to "Alle ansehen",

        // Listening Statistics
        "stats_title" to "Hörstatistiken",
        "stats_desc" to "Erfahre deine Hörgewohnheiten, Spitzenzeiten und Top-Künstler",
        "stats_btn_view" to "Statistiken ansehen",
        "stats_total_listening" to "Gesamte Hörzeit",
        "stats_today" to "Heute",
        "stats_this_week" to "Diese Woche",
        "stats_tracks_played" to "Gespielte Titel",
        "stats_peak_day" to "Aktivster Wochentag",
        "stats_peak_hours" to "Aktivste Tageszeit",
        "stats_day_breakdown" to "Aktivität nach Wochentag",
        "stats_time_breakdown" to "Aktivität nach Tageszeit",
        "stats_top_artists" to "Top Künstler",
        "stats_top_tracks" to "Meistgespielte Titel",
        "stats_empty_title" to "Noch kein Hörverlauf",
        "stats_empty_desc" to "Spiele Musik ab, um dein Hörprofil aufzubauen!",
        "stats_clear" to "Statistiken zurücksetzen",
        "stats_clear_confirm" to "Möchtest du die Hörstatistiken wirklich zurücksetzen?",

        // Lyrics
        "lyrics_title" to "Songtext",
        "lyrics_loading" to "Lade Songtext...",
        "lyrics_source_label" to "Quelle:",
        "lyrics_source_file" to "Eingebettet in Audiodatei",
        "lyrics_source_server" to "Navidrome Server",
        "lyrics_source_online" to "Online (LrcLib synchronisiert)",
        "lyrics_source_teksteshqip" to "Online (TeksteShqip)",
        "lyrics_teksteshqip_btn" to "TeksteShqip",
        "lyrics_teksteshqip_dialog_title" to "TeksteShqip Songtexte",
        "lyrics_teksteshqip_desc" to "TeksteShqip-Link eingeben oder albanische Songtexte suchen",
        "lyrics_teksteshqip_url_hint" to "https://teksteshqip.com/kuenstler/teksti/id",
        "lyrics_teksteshqip_fetch" to "Text laden",
        "lyrics_teksteshqip_search_auto" to "Automatisch auf TeksteShqip suchen",
        "lyrics_not_found" to "Kein Songtext für diesen Titel gefunden",
        "lyrics_not_found_desc" to "Datei, Navidrome-Server, LrcLib und TeksteShqip wurden überprüft.",
        "lyrics_tap_to_seek" to "Tippe auf eine Textzeile zum Springen",
        "lyrics_reload" to "Songtext neu laden",
        "lyrics_tab_artwork" to "Cover",
        "lyrics_tab_lyrics" to "Text",

        // App Updates
        "updates_section_title" to "App-Updates & GitHub Releases",
        "updates_current_version" to "Installierte Version",
        "updates_check_btn" to "Nach Updates suchen",
        "updates_checking" to "Prüfe GitHub Releases...",
        "updates_auto_check" to "Beim Start nach Updates suchen",
        "updates_auto_check_desc" to "Benachrichtigt automatisch, sobald ein neues APK auf GitHub veröffentlicht wird",
        "updates_new_available_title" to "Neues Update verfügbar!",
        "updates_uptodate_title" to "App ist auf dem neuesten Stand",
        "updates_uptodate_desc" to "Du nutzt bereits die aktuellste Version von GitHub.",
        "updates_install_btn" to "Herunterladen & Installieren",
        "updates_downloading" to "APK wird heruntergeladen...",
        "updates_ready_install" to "Bereit zur Installation",
        "updates_changelog" to "Änderungen / Was ist neu",
        "updates_view_on_github" to "Release auf GitHub ansehen",
        "updates_github_repo" to "GitHub Repository",
        "updates_dismiss" to "Später",
        "updates_update_now" to "Jetzt aktualisieren",
        "updates_never_checked" to "Noch nie geprüft",
        "updates_server_build" to "Server-Version",
        "updates_reinstall_btn" to "Vom Server installieren",
        "updates_last_checked" to "Letzte Prüfung",
        "updates_published" to "Bereitgestellt am",
        "updates_ready_to_install_title" to "Update bereit zur Installation",
        "updates_install_now_btn" to "Jetzt installieren",
        "updates_error_title" to "Fehler bei der Update-Prüfung",
        "updates_retry_btn" to "Wiederholen",
        "updates_repo_hint" to "Owner/Repo oder GitHub-URL eingeben",
        "updates_up_to_date_badge" to "Aktuell",
        "updates_installing" to "Update wird installiert...",
        "updates_preparing_installer" to "Paket-Installer wird gestartet...",
        "updates_installed_badge" to "Neueste Version installiert",

        // Sleep Timer
        "sleep_timer" to "Sleep-Timer",
        "sleep_timer_desc" to "Zeit auswählen, bis die Wiedergabe stoppt:",
        "sleep_timer_custom_min" to "Eigene Minuten",
        "sleep_timer_set_custom" to "Timer einstellen",
        "sleep_timer_turn_off" to "Sleep-Timer ausschalten",
        "sleep_timer_extra_actions" to "Aktionen nach Ablauf des Timers:",
        "sleep_timer_disable_bluetooth" to "Bluetooth ausschalten",
        "sleep_timer_disable_bluetooth_desc" to "Trennt verbundene Bluetooth-Audiogeräte",
        "sleep_timer_disable_wifi" to "WLAN ausschalten",
        "sleep_timer_disable_wifi_desc" to "Trennt die Verbindung zum WLAN-Netzwerk",
        "sleep_timer_disable_mobile_data" to "Mobiles Internet ausschalten",
        "sleep_timer_disable_mobile_data_desc" to "Trennt die mobile Datenverbindung",
        "sleep_timer_active_badge" to "Timer aktiv",
        "permission_bluetooth_needed" to "Bluetooth-Berechtigung ist erforderlich, um Bluetooth-Geräte auszuschalten",

        // Secure Settings & ADB Assistant
        "secure_settings_title" to "Secure Settings & ADB-Assistent",
        "secure_settings_badge_granted" to "Berechtigung aktiv",
        "secure_settings_badge_missing" to "Berechtigung erforderlich",
        "secure_settings_desc" to "Ab Android 10+ verhindert das System das stille Abschalten von WLAN, Bluetooth und mobilem Internet im Hintergrund. Mit der Berechtigung WRITE_SECURE_SETTINGS oder Root kann Navirom diese direkt deaktivieren.",
        "secure_settings_root_action" to "Auf diesem Gerät ausführen (Root / Shizuku)",
        "secure_settings_root_prompt" to "Möchtest du den ADB-Berechtigungsbefehl jetzt direkt auf diesem Gerät via Root/Shizuku ausführen?",
        "secure_settings_granting" to "Befehl wird ausgeführt...",
        "secure_settings_granted_success" to "Berechtigung erfolgreich erteilt! Stilles Abschalten ist jetzt aktiv.",
        "secure_settings_grant_failed" to "Automatische Ausführung fehlgeschlagen. Bitte Root/Shizuku prüfen oder den ADB-Befehl ausführen.",
        "secure_settings_copy_cmd" to "ADB-Befehl kopieren",
        "secure_settings_cmd_copied" to "ADB-Befehl in Zwischenablage kopiert!",
        "secure_settings_open_dev" to "Entwickleroptionen öffnen",
        "secure_settings_open_shizuku" to "Shizuku öffnen",
        "secure_settings_check_status" to "Status prüfen",
        "secure_settings_wireless_guide" to "Wireless Debugging / LADB: Der Befehl kann ohne PC direkt auf dem Gerät über Wireless Debugging mit Shizuku oder LADB ausgeführt werden.",
        "secure_settings_fallback_info" to "Ohne ADB/Root öffnet die App nach Ablauf des Timers bequem das System-Schnellmenü zum 1-Tap-Ausschalten.",
        "updates_highlights" to "Highlights & Neuerungen",
        "updates_view_changelog" to "Änderungsprotokoll & Details",

        // Local Folders
        "local_music_folders_title" to "Lokale Musik-Ordner",
        "local_music_folders_subtitle" to "Geräte-Ordner für Mediathek und Wiedergabe verwalten",
        "local_folders_active" to "%d von %d Ordner aktiv",
        "local_folder_all_active" to "Alle lokalen Ordner aktiv",
        "local_folder_deactivated" to "Ordner deaktiviert",
        "local_folder_enable_prompt" to "Ordner aktivieren um Titel abzuspielen",
        "scan_device_folders" to "Gerät scannen",
        "rescan_device_folders" to "Neu scannen",
        "no_local_folders_found" to "Keine lokalen Musik-Ordner auf dem Gerät gefunden",
        "local_folder_play_all" to "Ordner abspielen",
        "local_folder_shuffle" to "Ordner mischen",
        "select_all_local_folders" to "Alle aktivieren",
        "deselect_all_local_folders" to "Alle deaktivieren",
        "local_folders_header" to "Lokale Geräte-Ordner",
        "local_folders_settings_title" to "Lokale Musik-Ordner (Smartphone)",
        "local_folders_settings_desc" to "Wähle aus, welche Ordner deines Smartphones in der App und der Seitenleiste zur Verfügung stehen sollen.",
        "local_folders_settings_enabled_count" to "%d von %d Ordnern in App aktiviert",
        "local_folders_sidebar_info" to "Aktivierte Ordner erscheinen in der Seitenleiste zur schnellen Auswahl für die Wiedergabe.",
        "no_local_folders_enabled_in_settings" to "Keine Ordner in den Einstellungen aktiviert",
        "no_local_folders_sidebar_hint" to "Aktiviere lokale Ordner in den Einstellungen, damit sie hier in der Seitenleiste zur Auswahl stehen.",
        "btn_open_settings_folders" to "Ordner in Einstellungen verwalten",

        // Cover Quick Actions Sheet
        "cover_quick_actions_title" to "Schnellaktionen",
        "cover_quick_actions_desc" to "Countdown-Timer, Zeitsprung und Download",
        "countdown_timer_title" to "Countdown-Timer",
        "countdown_timer_active" to "Timer läuft",
        "countdown_timer_stop" to "Timer stoppen",
        "countdown_timer_start" to "Timer starten",
        "countdown_end_of_track" to "Song-Ende",
        "countdown_more_options" to "Weitere Timer-Optionen",
        "jump_to_time_title" to "Zu Zeit im Song springen",
        "jump_to_time_hint" to "z.B. 1:45 oder 90s",
        "jump_to_time_btn" to "Springen",
        "jump_to_time_invalid" to "Bitte gültige Zeit eingeben (z.B. 1:30)",
        "jump_quick_rewind" to "-30s",
        "jump_quick_forward" to "+30s",
        "jump_quick_start" to "Anfang (0:00)",
        "jump_quick_middle" to "Mitte (50%)",
        "download_this_song_btn" to "Diesen Song herunterladen",
        "download_this_song_desc" to "Für Offline-Wiedergabe ohne Internet speichern",
        "download_status_downloaded" to "Song ist offline verfügbar",
        "download_status_downloading" to "Song wird heruntergeladen...",
        "download_status_redownload" to "Erneut herunterladen",
        "download_status_failed" to "Download fehlgeschlagen - erneut tippen",
        "cover_open_lyrics" to "Songtext anzeigen"
    )
}
